from pathlib import Path
from html import escape as esc
from urllib.parse import quote
import json,re,xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parent.parent
BASE='https://2n2gzrsfdt-ai.github.io/price-finder/'
groups=[('iphone-17','iPhone 17',['256GB','512GB'],'https://www.apple.com/jp/newsroom/2025/09/apple-debuts-iphone-17/'),('iphone-17-pro','iPhone 17 Pro',['256GB','512GB','1TB'],'https://www.apple.com/jp/newsroom/2025/09/apple-unveils-iphone-17-pro-and-iphone-17-pro-max/'),('iphone-17-pro-max','iPhone 17 Pro Max',['256GB','512GB','1TB','2TB'],'https://www.apple.com/jp/newsroom/2025/09/apple-unveils-iphone-17-pro-and-iphone-17-pro-max/'),('iphone-16','iPhone 16',['128GB','256GB','512GB'],'https://www.apple.com/jp/newsroom/2024/09/apple-introduces-iphone-16-and-iphone-16-plus/'),('ipad-air-m4-11','iPad Air M4 11インチ',['128GB','256GB','512GB','1TB'],'https://www.apple.com/jp/ipad-air/specs/'),('ipad-air-m4-13','iPad Air M4 13インチ',['128GB','256GB','512GB','1TB'],'https://www.apple.com/jp/ipad-air/specs/')]
uses={'128GB':'文書やクラウド中心で使う場合の比較候補です。現在の端末で使っている容量に、写真・アプリ・ダウンロードの増加分を加えて判断してください。','256GB':'写真・アプリ・保存した動画を一台で扱う場合の比較候補です。使用済み容量と、今後端末内に残したいデータ量を見て選びましょう。','512GB':'動画やゲームなどを端末内に多く保存する場合の比較候補です。クラウドへ移せるデータと、オフラインで必要なデータを分けると判断しやすくなります。','1TB':'大きな動画素材や制作データを端末内に残す場合の比較候補です。容量が大きくてもバックアップは別途必要なので、その費用も合わせて検討しましょう。','2TB':'大量の動画素材を持ち歩く用途などで検討する容量です。必要なローカル保存量を確認し、1TBとの差額と外部保存の運用を比較してください。'}
items=[]
for slug,model,caps,source in groups:
 for cap in caps:items.append(dict(slug=slug+'-'+cap.lower(),model=model,capacity=cap,name=model+' '+cap,parent='ipad-air' if slug.startswith('ipad') else slug,source=source,caps=caps,group=slug))
css='''*{box-sizing:border-box}body{margin:0;background:#f4f6f9;color:#172033;font:16px/1.8 -apple-system,BlinkMacSystemFont,"Yu Gothic",Meiryo,sans-serif}main{max-width:1000px;margin:auto;padding:28px 18px}a{color:#1769d2}nav{display:flex;flex-wrap:wrap;gap:10px;font-size:14px}.box{background:white;border:1px solid #e0e5eb;border-radius:16px;padding:26px;margin:18px 0}h1{font-size:clamp(27px,6vw,42px);line-height:1.3}h2{font-size:23px}.muted,small{color:#667085}.btn{display:inline-block;background:#1769d2;color:white;padding:12px 18px;border-radius:10px;text-decoration:none;font-weight:700}.links{display:flex;flex-wrap:wrap;gap:9px}.links a{background:#eef3fa;padding:8px 12px;border-radius:9px;text-decoration:none}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #e4e8ee;padding:12px;text-align:left}th{width:30%}.tablewrap{overflow:auto}.offer{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;padding:18px 0;border-bottom:1px solid #e4e8ee}.offer b{display:block}.offer .amount{font-size:22px}.offer a{align-self:center}.notice{background:#eef5fc;padding:16px;border-radius:10px}button{font:inherit;cursor:pointer;padding:8px 14px;border:1px solid #cbd5e1;background:white;border-radius:8px}details{border-top:1px solid #e4e8ee;padding:12px 0}summary{cursor:pointer;font-weight:700}footer{font-size:13px;color:#667085;padding:18px 0}@media(max-width:600px){main{padding:18px 12px}.box{padding:20px}.offer{grid-template-columns:1fr}th{width:34%}}'''
(ROOT/'assets/product-pages.css').write_text(css)
for p in items:
 name=esc(p['name']); url=BASE+p['slug']+'.html'; query=p['name']; tablet=p['group'].startswith('ipad');
 variant='M4・'+('11インチ' if '-11' in p['group'] else '13インチ')+'・'+p['capacity'] if tablet else p['capacity']
 rows=[('機種・容量',p['name']),('通信・販売条件','Wi-Fi / Wi-Fi + Cellularをそろえる。M2・M3世代とは分けて比較。' if tablet else '国内向け / 海外向け、SIM条件、回線契約の有無をそろえる。'),('状態','新品・未使用・中古・整備済みを分ける。中古は保証と付属品も確認。'),('支払総額','商品価格＋送料＋必須手数料。ポイントやクーポンは適用条件を別途確認。')]
 caplinks=''.join(f'<a href="./{p["group"]}-{c.lower()}.html"'+(' aria-current="page"' if c==p['capacity'] else '')+f'>{esc(c)}</a>' for c in p['caps'])
 related=[x for x in items if x['capacity']==p['capacity'] and x['group']!=p['group']][:4]
 relatedhtml=''.join(f'<a href="./{x["slug"]}.html">{esc(x["name"])}</a>' for x in related)
 faqs=[(f'{p["capacity"]}だけの結果ですか？','商品名から機種・容量を確認して表示しますが、ショップの表記によって取りこぼしや異なる条件の商品が含まれる可能性があります。購入先で型番・容量・状態を必ず確認してください。'),('最安値は何を基準にしていますか？','取得できた商品の範囲で価格を比較します。送料が未取得の商品は総額比較の対象外です。ポイント・個別クーポン・回線契約の割引は含みません。'),('価格が表示されない場合は？','APIの応答や在庫、商品名の表記によって表示できない場合があります。価格を作って表示することはありません。検索画面で条件を変えるか、各ショップで直接確認してください。')]
 schema={'@context':'https://schema.org','@type':'BreadcrumbList','itemListElement':[{'@type':'ListItem','position':1,'name':'PRICE FINDER','item':BASE},{'@type':'ListItem','position':2,'name':'商品別価格比較','item':BASE+'products.html'},{'@type':'ListItem','position':3,'name':p['name'],'item':url}]}
 desc=p['name']+'の価格比較。機種・容量・状態・送料を確認し、楽天市場とYahoo!ショッピングの購入候補を探せます。'
 html=f'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{name}の価格比較・送料確認｜PRICE FINDER</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="{url}"><meta property="og:title" content="{name}の価格比較"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><link rel="stylesheet" href="./assets/product-pages.css"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script></head><body><main><nav aria-label="パンくず"><a href="./">PRICE FINDER</a><span>›</span><a href="./products.html">商品別価格比較</a><span>›</span><span aria-current="page">{name}</span></nav><section class="box"><p class="muted">機種と容量をそろえて比較</p><h1>{name}の価格比較</h1><p>{esc(p['model'])}の{esc(p['capacity'])}を探すページです。安く見える商品でも、状態や通信条件が違うことがあります。下の比較では商品名と送料の取得状況を確認できます。</p><a class="btn" href="./?q={quote(query)}#search">条件を変えて価格比較</a></section><section class="box" id="comparison" data-query="{esc(query)}" data-model="{esc(p['model'])}" data-capacity="{p['capacity']}"><h2>{name}の購入候補</h2><p class="muted">楽天市場・Yahoo!ショッピングから取得できた情報を表示。全販売店の最安値を保証するものではありません。</p><p id="price-status" role="status" aria-live="polite">価格情報を確認しています…</p><div id="price-offers"></div><button id="retry-prices" type="button">価格を再取得</button><noscript><p>価格の自動取得にはJavaScriptが必要です。上の比較リンクから検索するか、ショップで確認してください。</p></noscript></section><section class="box"><h2>同じ条件で比べるチェック表</h2><div class="tablewrap"><table><tbody>{''.join('<tr><th scope="row">'+esc(k)+'</th><td>'+esc(v)+'</td></tr>' for k,v in rows)}</tbody></table></div><p class="notice">対象は{esc(variant)}。ケース・フィルム・分割払いの月額表示と、本体の一括価格を混同しないよう確認してください。</p></section><section class="box"><h2>{p['capacity']}を選ぶ前に</h2><p>{uses[p['capacity']]}</p><p>容量だけを増やしても、通信方式や保証条件が同じになるわけではありません。下の容量別ページで、使い方に合う候補の支払総額を比べてください。</p><div class="links">{caplinks}</div><p><a href="{p['source']}" rel="noopener">Apple公式のモデル・容量情報</a></p></section><section class="box"><h2>価格と送料の読み方</h2><p>送料を取得できた商品は「商品価格＋送料」を表示します。送料未確認の商品は商品価格だけを表示し、総額の順位には入れません。地域や注文条件による追加料金は購入先で確認してください。</p><p>新品と中古の価格差には、使用状態・保証・付属品の差が含まれます。ポイント還元を現金値引きとして扱わず、利用条件や有効期限も確認しましょう。</p></section><section class="box"><h2>よくある質問</h2>{''.join('<details><summary>'+esc(q)+'</summary><p>'+esc(a)+'</p></details>' for q,a in faqs)}</section><section class="box"><h2>関連する価格比較</h2><div class="links">{relatedhtml}<a href="./{p['parent']}.html">{esc(p['model'])}の関連ページ</a><a href="./products.html">容量別ページ一覧</a></div></section><footer>当サイトはアフィリエイトプログラムを利用しています。購入によって運営者に紹介料が入る場合があります。価格・送料・在庫・保証の最終条件は購入先でご確認ください。</footer></main><script src="./assets/product-prices.js" defer></script></body></html>'''
 (ROOT/(p['slug']+'.html')).write_text(html)
hub=''.join('<section class="box"><h2>'+esc(model)+'</h2><div class="links">'+''.join(f'<a href="./{x["slug"]}.html">{esc(x["name"])}</a>' for x in items if x['group']==slug)+'</div></section>' for slug,model,caps,source in groups)
(ROOT/'products.html').write_text('<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>機種・容量別の価格比較一覧｜PRICE FINDER</title><meta name="description" content="iPhoneとiPad Airの機種・容量別に購入候補を比較。送料、通信条件、商品状態も確認できます。"><link rel="canonical" href="'+BASE+'products.html"><link rel="stylesheet" href="./assets/product-pages.css"></head><body><main><nav><a href="./">PRICE FINDER</a></nav><h1>機種・容量別の価格比較</h1><p>欲しい機種と容量を選び、同じ条件の購入候補を探せます。</p>'+hub+'</main></body></html>')
marker='<!-- capacity-pages:start -->';end='<!-- capacity-pages:end -->'
for parent in sorted(set(x['parent'] for x in items)):
 f=ROOT/(parent+'.html');s=f.read_text();block=marker+'<section class="box"><h2>容量を指定して価格比較</h2><div class="related">'+''.join(f'<a href="./{x["slug"]}.html">{esc(x["name"])}</a>' for x in items if x['parent']==parent)+'</div></section>'+end
 s=re.sub(re.escape(marker)+'.*?'+re.escape(end),'',s,flags=re.S);s=s.replace('</main>',block+'</main>');f.write_text(s)
f=ROOT/'index.html';s=f.read_text();s=re.sub(re.escape(marker)+'.*?'+re.escape(end),'',s,flags=re.S);s=s.replace('</body>',marker+'<section class="section" style="max-width:1040px;margin:auto"><div class="card"><h2>機種・容量から価格比較</h2><p>iPhone・iPad Airを容量まで指定して探せます。</p><a class="secondary" href="./products.html">20種類の比較ページを見る</a></div></section>'+end+'</body>');f.write_text(s)
f=ROOT/'sitemap.xml';ns='http://www.sitemaps.org/schemas/sitemap/0.9';ET.register_namespace('',ns);tree=ET.parse(f);root=tree.getroot();present={x.text for x in root.findall('{'+ns+'}url/{'+ns+'}loc')}
for path in ['products.html']+[x['slug']+'.html' for x in items]:
 if BASE+path not in present:
  u=ET.SubElement(root,'{'+ns+'}url');ET.SubElement(u,'{'+ns+'}loc').text=BASE+path
ET.indent(tree,space='  ');tree.write(f,encoding='utf-8',xml_declaration=True)
print('Generated',len(items),'comparison pages and directory')
